<?php $_categories = $this->getStoreCategories() ?>
<?php if(count($_categories)): ?>
<style>
.dropdown-submenu {
    position: relative;
}

.dropdown-submenu .dropdown-menu {
    top: 0;
    left: 100%;
    margin-top: -1px;
}
</style>
<nav class="nav-container">
	<div class="nav-inner">
    <div id="advancedmenu">
        <?php if ($this->showHomeLink()) : ?>
        <div class="menu">
            <div class="parentMenu menu0 home_link">
                <a href="<?php echo $this->getUrl('') ?>">
                    <span><?php echo $this->__('Home'); ?></span>
                </a>
            </div>
	     </div>
		  
		  
		 <?php endif ?>
        <?php foreach ($_categories as $_category): ?>
			<?php echo $this->drawAdvancedMenuItem($_category) ?>
		<?php endforeach ?>
        
		<?php if ($this->isActivecustomBlock()) : 
			$custom_block_name =  Mage::getStoreConfig('advanced_menu/customblock/menucustomblock_name'); 
			$custom_block_identifier =  Mage::getStoreConfig('advanced_menu/customblock/customblock_identifier'); 
			$custom_topoffset = Mage::getStoreConfig('advanced_menu/popup/top_offset') + 0;
		?>
			
			<div class="custom_menu">
				<div class="menu"><a class="custom_menu_block"><span><?php echo $custom_block_name; ?></span></a></div>
				<div class="customblock_inner" style="top:<?php echo $custom_topoffset; ?>px">
					<div class="megnor-advanced-menu-popup_inner">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block_identifier)->toHtml() ?> 
					</div>	
				</div>
			</div>
		<?php  endif?>	
		
		
		<div class="clearBoth"></div>
    </div>
	
	<!--- Code for responsive menu start Veena - MAG--->
	<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
	<?php /*Mage::Log($_menu); */?>

	
	
	<div class="nav-responsive" style="display:none;"><span>Menu</span><div class="expandable"></div></div>
		<ul id="nav" class="advanced_nav" >
			<?php echo $_menu ?>
		</ul>
	 
</div>	

</nav>
<script type="text/javascript">
//<![CDATA[
var CUSTOMMENU_POPUP_WIDTH = <?php echo Mage::getStoreConfig('advanced_menu/popup/width') + 0; ?>;
var CUSTOMMENU_POPUP_TOP_OFFSET = <?php echo Mage::getStoreConfig('advanced_menu/popup/top_offset') + 0; ?>;
var CUSTOMMENU_POPUP_RIGHT_OFFSET_MIN = <?php echo Mage::getStoreConfig('advanced_menu/popup/right_offset_min') + 0; ?>;
var CUSTOMMENU_POPUP_DELAY_BEFORE_DISPLAYING = <?php echo Mage::getStoreConfig('advanced_menu/popup/delay_displaying') + 0; ?>;
var CUSTOMMENU_POPUP_DELAY_BEFORE_HIDING = <?php echo Mage::getStoreConfig('advanced_menu/popup/delay_hiding') + 0; ?>;
var megnorCustommenuTimerShow = {};
var megnorCustommenuTimerHide = {};
//]]>
</script>
<?php endif ?>

 