<?php
  /*
  * Copyright (c) 2013 www.magebuzz.com
  */
?>
<?php
  /**
  * Shopping cart template
  *
  * @see Mage_Checkout_Block_Cart
  */
?>
<?php
		 $collectproduct = array();
         foreach($this->getItems() as $_item): 

          	  $product = Mage::getModel('catalog/product')->load($_item->getProductId());

	          $_product = Mage::getModel('catalog/product');
	          $_productId = $_product->getIdBySku($_item->getSku());


                $p = Mage::getModel('catalog/product')->load($_productId);		
		$cats = $p->getCategoryIds();	
		foreach ($cats as $category_id){
		    $category = Mage::getModel('catalog/category')->load($category_id) ;
			if(!empty($category)){
			    $curcatid= $category->getId();
			    $it = 10;    
			    if ( $category) {
			        while( $category->getLevel() != 2 && $it > 0) {
			             $category =  $category->getParentCategory();        
			            if (! $category) {
			                break;
			            }
			        }        
			        if ( $category && strtolower($category->getName()) != "dailyupdate") {
			            $toplevelcatid= $category->getId();
			        }
			        else {        	
			            //echo 'Cannot find parent category';
			        }
			    }
			}
		}

	          //$_product->load($_productId);
         /*
	          $topCategory = Mage::getResourceModel('catalog/category_collection')
	          ->addIdFilter($product->getCategoryIds())
	          ->setOrder('level', 'ASC')
	          ->setPage(1,1)
	          ->getFirstItem();
	   */       
	          $_cat = Mage::getModel('catalog/category')->load($toplevelcatid); //$topCategory->getId();
	          //if(findKey($collectproduct, $topCategory->getId()))
	          $catName = $_cat->getName(); 
	          $item = clone $_item;
	          //$collectproduct[] = $_item;
	          //$collectproduct.push($_item);
	          if(!isset($collectproduct[$catName]))
	          	$collectproduct[$catName] = array();
	          
	          array_push($collectproduct[$catName], $_item->getId()."@#@#".$_productId);
	          
          endforeach;
          //print_r($collectproduct);

          
?>
 <?php
        $storeId = Mage::app()->getStore()->getWebsiteId();
        $minOrderActive = Mage::getStoreConfigFlag('sales/minimum_order/active', $storeId);
        $minAmount      = Mage::getStoreConfig('sales/minimum_order/amount', $storeId);
        $freeActive   = Mage::getStoreConfigFlag('carriers/tablerate/active', $storeId);
        $cart = Mage::getModel('checkout/cart')->getQuote()->getSubtotal();
        
        $read = Mage::getSingleton('core/resource')->getConnection('core_read');
        $sql = "SELECT * FROM shipping_tablerate where `website_id`=$storeId";
        $readresult = $read->query($sql);

        while ($row = $readresult->fetch() ) {
          if($row['condition_value']>0)
            $freeAmount = $row['condition_value'];
        }  
        if ($minOrderActive) {
             $diff = $minAmount-$cart;
             if($diff>0) 
              $msg =  "Add items worth Rs. $diff  to checkout";
        }
        else if($freeActive) {
           $diff = $freeAmount-$cart;
             if($diff>0) 
              $msg =  "Add items worth Rs. $diff to qualify for free shipping";

        }
        
        ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/shoppinglist/colorbox.css')?>" media="screen" />
<script type="text/javascript" src="<?php echo $this->getJsUrl('magebuzz/shoppinglist/jquery.colorbox.js')?>"></script>
<div class="cart">
  <div class="page-title title-buttons">
    <h1 style="float:left;"><?php echo $this->__('Shopping Cart') ?></h1>
	<a style="float:left; padding: 12px 0 0 5px;" href="<?php echo Mage::getUrl('emptyCart/')?>">
		<?php echo Mage::helper('core')->__("(Empty Cart)");?>
	</a>
  
    <?php if(!$this->hasError()): ?>
      <ul class="checkout-types">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
          <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
          <?php endforeach; ?>
      </ul>
      <?php endif; ?>
  </div>
  <?php echo "<div class='min-msg'>$msg</div>";?>
  <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
  <?php echo $this->getChildHtml('form_before') ?>
  <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
   <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
    <fieldset>
      <table id="shopping-cart-table" class="data-table cart-table">
        <col width="1" />
        <col />
        <col width="1" />
        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
          <col width="1" />
          <?php endif ?>
        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
          <col width="1" />
          <?php endif; ?>
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
          <col width="1" />
          <?php endif; ?>
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
          <col width="1" />
          <?php endif; ?>
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
          <col width="1" />
          <?php endif; ?>
        <col width="1" />

        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
        <thead>
          <tr>
            <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
			
          <th rowspan="<?php echo $mergedCells; ?>">Brand</th>
		  <th class="a-center">Pack Size</th>
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
              <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
              <?php endif ?>
            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
          </tr>
          <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
              <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
              <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
              <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
              <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            </tr>
            <?php endif; ?>
        </thead>
        <tfoot>
          <tr>
            <td colspan="50" class="a-right">
              <?php if($this->getContinueShoppingUrl()): ?>
                <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                <?php endif; ?>
              <?php if (Mage::helper('shoppinglist')->isActive() && Mage::helper('shoppinglist')->isShowSaveForLater()) : ?>
                <?php $countItem = Mage::helper('checkout/cart')->getItemsCount();
                  if($countItem >0){                  
                  ?>
                  <button type="button" title="<?php echo $this->__('Save as Quick List') ?>" class="button btn-save-later">
		    <span><span><?php echo $this->__('Save as Quick List') ?></span></span>
		  </button>
                  <?php }?>
                <?php endif; ?>
              <button type="submit" title="<?php echo $this->__('Update Shopping Cart') ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart') ?></span></span></button>
            </td>
          </tr>
        </tfoot>
        <tbody>
        
        <?php

			/* $product = Mage::getModel('catalog/product')->load($_item->getProductId());
			$cats = $product->getCategoryIds();
			$categoryName	=	"";
			foreach ($cats as $category_id) {				
				$_cat = Mage::getModel('catalog/category')->load($category_id);
				$categoryName	.=	$_cat->getName().", ";
			}
			echo rtrim($categoryName,", "); */
		?>
        
          <?php
          
    	      if(!$quoteObj)
	          	$quoteObj = new Mage_Sales_Model_Quote();          
              $storeId = Mage::app()->getStore()->getStoreId();
              
	          foreach($collectproduct as $key => $value) {
				echo "<tr><th colspan='8'>".$key."</th></tr>";
	          	foreach($value as $key => $val) {

					$valsplit = explode("@#@#", $val);
	          		$_product = Mage::getModel('catalog/product')->load($valsplit[1]);	          		
	          		$item = Mage::getModel('sales/quote_item')->setProduct($_product)->setQuote($quoteObj)->setStoreId($storeId)->load($valsplit[0]);
	          		echo $this->getItemHtml($item);
	          		
	          	}
	          }
          
	         /*  foreach($this->getItems() as $_item):
	          	  
	          	  $storeId = Mage::app()->getStore()->getStoreId();
	              	          

	              $_product = Mage::getModel('catalog/product');
	              $_productId = $_product->getIdBySku($_item->getSku());
	              $_product->load($_productId);	 
	                           
	              if(!$quoteObj)
	              	$quoteObj = new Mage_Sales_Model_Quote();
	          	  $item = Mage::getModel('sales/quote_item')->setProduct($_product)->setQuote($quoteObj)->setStoreId($storeId)->load("728");	          	  
	           
	              echo $this->getItemHtml($item);
	              
	          endforeach;
 */           ?>
        </tbody>
      </table>
      <script type="text/javascript">decorateTable('shopping-cart-table')</script>
    </fieldset>
  </form>
  <div class="eligible_for_coupon">
    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('eligible_for_coupon')->toHtml(); ?>
  </div>
  <div class="cart-collaterals">
    <div class="col1-set">
      <!-- <div class="col-1">
        <?php //echo $this->getChildHtml('crosssell') ?>
      </div> -->
      <div class="col-1">
        <?php echo $this->getChildHtml('coupon') ?>
	<?php //echo $this->getChildHtml('checkdelivery') ?>
        <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
      </div>
    </div>
    <div class="totals">
      <?php echo $this->getChildHtml('totals'); ?>
      <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
          <?php foreach ($this->getMethods('methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
              <li><?php echo $methodHtml; ?></li>
              <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </div>
  </div>
</div>
<div style="display:none;">
  <div id="addquicklist" style='padding:20px; background:#fff;'>
    <?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
     <form action="<?php echo $this->getUrl('shoppinglist/index/savelater')?>" method="post" id="form-add-quick-list">
      <div class="form-add">      
	<ul class="form-list">        
	  <li>
	    <div id="form-create-group" style="">
	      <label for="group-name" class="required"><em>*</em>Quick List Name</label>
	      <div class="input-box">
		<input name="group-name" id="group-name" title="Group Name" value="" class="input-text required-entry" type="text">
	      </div>
	    </div>
	  </li>        
	</ul>
	<div class="buttons-set">
	  <p class="required">* Required Fields</p>
	  <button class="button btn-submit right" id="btn-submit-add-quick-list" title="Submit" type="submit">
	    <span><span>Submit</span></span>
	  </button>        
	</div>
      </div>
    </form>
    <?php else: ?>
      <div class="form-add">
	  You should be logged in to use this feature. Please Login <a href="<?php echo $this->getUrl("customer/account/login/"); ?>">here</a>.
      </div>
    <?php endif; ?>
  </div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function(){    
    jQuery(".btn-save-later").colorbox({inline:true, href:"#addquicklist"});
    jQuery("#form-add-quick-list").submit(function(){
      if (jQuery("#group-name").val()=="") {
	jQuery("#group-name").addClass('validation-failed');
	jQuery(".validation-advice").remove();
	jQuery("#group-name").append('<div class="validation-advice" id="advice-required-entry-group-name">This is a required field.</div>');
	return false;
      }      
    });
  });
</script>