<?php 
  /*
  * Copyright (c) 2013 www.magebuzz.com
  */

  $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<div class="no-display">
  <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
  <input type="hidden" name="related_product" id="related-products-field" value="" />
</div>
<div class="product-shop">
  <?php echo $this->getChildHtml('product_type_data') ?>
  <?php if ($_product->isSaleable() && $this->hasOptions()):?>
    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
    <?php endif;?>
</div>
<?php echo $this->getCHildHtml('product_options_wrapper_bottom')?>