<?php
  /*
  * Copyright (c) 2013 www.magebuzz.com
  */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<ul class="add-to-links" style="margin-left:12px;">
  <?php if ($this->helper('wishlist')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
    <?php endif; ?>
  <?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
  ?>
  <?php //if($_compareUrl) : ?>
<!--    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
-->    <?php //endif; ?>
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()):?>
  <?php if (Mage::helper('shoppinglist')->isActive()) : ?>
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
      <?php $_shoppingListUrl = $this->getUrl('customer/account/login');?>
      <li><span class="separator">|</span> <a href="<?php echo  $this->getUrl('shoppinglist/item/login',array('id'=> $_product->getId(), 'type' => $_product->getTypeId())); ?>" class="link-shoppinglist" ><?php echo $this->__('Add to quick list') ?></a></li>
      <?php else:?>
      <?php $_shoppingListUrl = Mage::getUrl('shoppinglist/index/add',array('id'=> $_product->getId(), 'type' => $_product->getTypeId())); ?>
      <li><span class="separator">|</span> <a href="<?php echo $_shoppingListUrl;?>" url="<?php echo $_shoppingListUrl;?>" id="openFormAdd_<?php echo $_product->getId(); ?>" class="link-shoppinglist"><?php echo $this->__('Add to quick list') ?></a></li>

      <?php endif;?>
    <?php endif;?>
	 <?php endif;?>
</ul>
<script type="text/javascript">
  function addToShoppingList(url) {
    var form = $('product_addtocart_form');
    if (form){
      var validator = new Validation(form);
      if (validator.validate()) {
        var data = form.serialize();
        jQ.colorbox({
          href:"<?php echo Mage::getUrl('shoppinglist/index/detailform/'); ?>"+ "?" +data
        });
      }
      //			
    }
    else
      document.location.href = url;      
    return false;
  }
</script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery(".link-shoppinglist").click(function(e){	
	    //var prodid = jQuery(this).attr("id");	    
	    //prodid = prodid.split("_");
	    //prodid = prodid[1];
	    var size = jQuery("#product_addtocart_form").find(".amconf-image-selected").attr("id");
	    size = size.split("amconf-image-");
	    size = size[1].split("-");
	    size = size[0];
	    var url = jQuery(this).attr("url");
	    var newurl = url + "?size=" + size;
	    if(jQuery("#product_addtocart_form_"+prodid).find(".amconf-image-selected").hasClass("amconf-sold-out")) {
		newurl += "&soldout=1"
	    }	    
	    jQuery(this).attr("href", newurl);   
	    return true;
        });              
    });
</script>