<?php if (!Mage::getStoreConfig("ddate/info/calender_display")) { ?>                                  
    <?php
    $slots = $this->getSlots();
    $currentTime = Mage::getSingleton('core/date')->timestamp();
    $weeks = $this->getNumberWeek();
    $deliveryslot = array();//[];
    for ($w = 0; $w < $weeks; $w++){		    
		    foreach($slots as $slot) {
				for ($i = 2 * $w; $i < 2 * $w + 2; $i++) {							    
				    $strDate = date('Y-m-d', strtotime('+' . $i . ' day', $currentTime));
				    //echo $strDate;
				    if($this->isEnabled($slot->getId(), $strDate)){
						$deliveryslot[] = date('Y-m-d', strtotime('+' . $i . ' day', $currentTime))." ".$slot->getDtime();							    
				    }else{
						$deliveryslot[] = "unavailable";
				    }
				}
		    }
    }
   
   // $deliveryorder = array(0, 2, 4, 6, 1, 3, 5, 7, 8, 10, 12, 14, 9, 11, 13, 15);
    $neworder = array();//[];
    $x = 0;
       
    $count = count($slots);
    $m =0;
    $n=$count+1;
       for($k=0;$k<$count*2;$k++) {
            $order = $k;
            if($order%2==0) {
                $deliveryorder[$m] = $order;
                
                $deliveryorder[$m+ $count*2+1] = $k+ $count*2;
                $m++;
            }
            else {
                $deliveryorder[$n] = $k;
                 $deliveryorder[$n+ $count*3] = $k+ $count*2;
                $n++;
               
            }
        
        }
        ksort($deliveryorder);

    foreach($deliveryorder as $ds){
    	$neworder[$x] = $deliveryslot[$ds];
    	$x++;
    }
    
    foreach($neworder as $key=>$value){
		if($value != "unavailable"){
		    $earlisttimeslot = $value;
		    break;
		}
    }
}
?>
<div class="earlist-time-slot" style="display: none;">
<?php echo "<li>Next delivery slot:</li> <li class='deliver-slot'>".$earlisttimeslot."</li>"; ?>
</div>