<?php
  /*
  * Copyright (c) 2013 www.magebuzz.com
  */
?>
<form id="shoppinglist-view-form" action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
  <table class="data-table" id="shoppinglist-table">
    <thead>
      <tr>
        <th><span class="nobr"><?php echo $this->__('Product')?></span></th>
        <th><span class="nobr"><?php echo $this->__('Description')?></span></th>
        <th><span class="nobr"><?php echo $this->__('Added on')?></span></th>
        <th><span class="nobr"><?php echo $this->__('Add to cart')?></span></th>
        <th><span class="nobr"><?php echo $this->__('Group')?></span></th>
      </tr>
    </thead>
  </table>
</form>
