<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @author        Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
 <div class="featured-products">
<div class="category-title"><h2><a href="<?php echo $this->getUrl('') ?>/featured-products"><?php echo $this->__($this->getBlockLabel()) ?></a></h2></div>

<?php if(!$this->getProductCollection()->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?> 
<?php if (($_productCollection = $this->getProductCollection()) && $_productCollection->getSize()): ?>
 
	<?php // Grid Mode ?>
    <?php $_collectionSize = $_productCollection->count() ?>
 	
		<?php 
		$sliderFor = 5;
		$productCount = $_collectionSize; 
	?>
	<?php if ($productCount >= $sliderFor): ?>
		<div class="customNavigation">
			<a class="btn prev">&nbsp;</a>
			<a class="btn next">&nbsp;</a>
		</div>	
	<?php endif; ?>	

        <ul class="<?php if ($productCount >= $sliderFor){?>product-carousel<?php }else{?>products-grid<?php }?>" id="<?php if ($productCount >= $sliderFor){?>featured-carousel<?php }else{?>featured-grid<?php }?>">
            
			<?php  $i = 0; $row = 0; foreach ($_productCollection->getItems() as $_product):  ?>
            
			      <li class="item <?php if ($productCount >= $sliderFor){?>slider-item<?php }else{?>product-items<?php }?>">   
				  <div class="product-block-image">
				  	<div class="product-block">
						<div class="product-block-inner">
				           
						<?php if($this->helper('framework')->isNewProduct($_product)):?>
							<div class="new-label"><?php echo $this->__('New') ?></div>
						<?php endif; ?>
						
						<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
							<div class="sale-label"><?php echo $this->__('Sale') ?></div>
						<?php endif; ?>
					 
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200,250); ?>" width="200" height="250" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						
                        <h2 class="product-name">
						
                            <?php //echo $this->escapeHtml($_product->getName()) 
							$str = strlen($_product->getName());
							if($str <= 20 )
							{ ?>
										
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>)">
									<?php echo $this->escapeHtml($_product->getName()) ?>
								</a>
							<?php }
							else
							{ ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn">
								<?php echo substr($this->escapeHtml($_product->getName()),0,20) .".." ?>
							   </a>
							 <?php  } ?>
							
						</a>
							</h2>
							
					
                           <?php echo $this->getPriceHtml($_product, true, '-new') ?>
  							
							<div class="hover_block">
								
							 <?php if ($_product->isSaleable()): ?>
							
							 <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
 <div class="quantity">
<input type="text" name="qty" id="qty" maxlength="12" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
</div>
<button type="button" class="button btn-cart" onclick="productAddToCartForm_<?php echo $_product->getId(); ?>.submit()"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
</form>
<script type="text/javascript">
     var productAddToCartForm_<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
     productAddToCartForm_<?php echo $_product->getId(); ?>.submit = function(){
     if (this.validator.validate()) {
             this.form.submit();
         }
     }.bind(productAddToCartForm_<?php echo $_product->getId(); ?>);
</script>
							
							
							
							
							
							<?php else: ?>
								<div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
                             <?php endif; ?>
								
								<div class="actions">
                               	 <ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										
									</ul>
							</div>
							
							</div>
							
							
                      
						
					</div><!-- End div class product-block-->
					</div><!-- End div class product-block-inner -->
					</div>
               </li>        
    <?php endforeach; ?>
        </ul> 
</div>
<span class="featured_default_width" style="display:none; visibility:hidden"></span>
<?php endif; ?>
<?php endif; ?>
 
 
 <script>
jQuery("div.quantity").append('<input type="button" value="+" id="add1" class="plus" />').prepend('<input type="button" value="-" id="minus1" class="minus" />');
        jQuery(".plus").click(function()
        {
            var currentVal = parseInt(jQuery(this).prev(".qty").val());
           
            if (!currentVal || currentVal=="" || currentVal == "NaN") currentVal = 0;
             
            jQuery(this).prev(".qty").val(currentVal + 1);
        });
     
        jQuery(".minus").click(function()
        {
            var currentVal = parseInt(jQuery(this).next(".qty").val());
            if (currentVal == "NaN") currentVal = 0;
            if (currentVal > 0)
            {
                jQuery(this).next(".qty").val(currentVal - 1);
            }
        });
         </script>