<?php
  /*
  * Copyright (c) 2013 www.magebuzz.com
  */

  $_customer = Mage::getSingleton('customer/session')->getCustomer();?>
<?php $group_id = $this->getRequest()->getParam('id'); ?>
<?php $gmodel = Mage::getModel('shoppinglist/group');?>
<?php $_helper = Mage::helper('shoppinglist/group');?>
<?php $items = $this->getGroup()->getItems();?>
<?php $group = $gmodel->load($group_id);?>
<script type="text/javascript">

  function selectAllProduct(source){
    checkboxes = document.getElementsByName('selectproduct');
    for(var i=0, n=checkboxes.length;i<n;i++) {      
      checkboxes[i].checked = source.checked;
    }
  }
  function choiceAction(action){
    if(action == 'addselect'){
      document.getElementById('addselecttocart').style.display ='block';
    }else{
      document.getElementById('addselecttocart').style.display ='none';     
    }
    if(action == 'delselect'){
      document.getElementById('deleteselect').style.display ='block';
    }else{
      document.getElementById('deleteselect').style.display ='none';     
    }
  }
  function getListProduct(){
    var listitem = new Array();
    checkboxes = document.getElementsByName('selectproduct');
    for(var i=0, n=checkboxes.length;i<n;i++) {
      if(checkboxes[i].checked==true){
        listitem[i] = checkboxes[i].value;    
      }      
    }
    if(listitem.length>0){
      return listitem;     
    }else{
      return false;
    }

  }

</script>
<div class="my-shoppinglist">
  <div id="messages_shoppinglist"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>	
  <div class="customer-group-view">
    <div class="page-title title-buttons">
      <h2><?php echo $this->__('%s', $group->getListName())?></h2>
    </div>
    <form name="shoppinglist-group-view" id="shoppinglist-group-view" action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
      <div class="change-group-name">
        <label><?php echo $this->__('Change Quick List Name');?>: </label>
        <input class="input-text required-entry" type="text" name="list_name" value="<?php echo $group->getListName(); ?>" />	
      </div>			
      <?php if(count($items) > 0): ?>
        <table class="data-table" id="customer-group-table">
          <colgroup>
            <col width="1"/>
            <col />
            <col width="1"/>
            <col width="1"/>
            <col width="1"/>
            <col/>
            <col width="1"/> 
            <col/>
          </colgroup>
          <thead>
            <tr>
              <th class="a-center"><span class="nobr"><?php echo $this->__('Product Image')?></span></th>
              <th class="a-left"><span class="nobr"><?php echo $this->__('Description')?></span></th>
              <th class="a-center"><span class="nobr"><?php echo $this->__('Qty')?></span></th>
              <th class="a-center"><span class="nobr"><?php echo $this->__('Price')?></span></th>
              <th class="a-center"><span class="nobr"><?php echo $this->__('Move to other List')?></span></th>
              <th class="a-center"><span class="nobr"><?php echo $this->__('Status')?></span></th>
              <th class="a-center"><span class="nobr"></span></th>
              <th class="a-center"><span class="nobr"></span><!--<input type="checkbox" name="selectallproduct" id="selectallproduct" onlick="selectAllProduct(this)"/>--></th>    
            </tr>	
          </thead>
          <tbody>
            <?php foreach($items as $_item):?>
              <?php 
                $product_id = $_item->getProductId();
                $product = Mage::getModel('catalog/product')->load($product_id);
                $isVisibleProduct = $product->isVisibleInSiteVisibility();
              ?>
              <tr>
                <td class="a-center"><span><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($product->getName()) ?>" class="product-image"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')->resize(75, 75); ?>" width="75" height="75" alt="<?php echo $this->escapeHtml($product->getName()) ?>" /></a></span></td>              
                <td class="a-left">                
                  <h3 class="product-name"><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($product->getName()) ?>"><?php echo $this->htmlEscape($product->getName()) ?></a></h3>
                  <!-- PRINT OPTIONS OF PRODUCT HERE -->
                  <?php echo $_item->getOptionsHtml() ?>
                </td>
                <td class="a-center">
                  <input name="item[<?php echo $_item->getItemId() ?>][itemId]" type="hidden" value="<?php echo $_item->getItemId(); ?>"/> 
                  <input name="item[<?php echo $_item->getItemId() ?>][qty]" value="<?php echo $_item->getQty()*1 ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="required-entry validate-number validate-zero-or-greater" maxlength="12" />
                </td>
                <td class="a-left">
                  <?php echo Mage::helper('core')->currency($_item->getPrice());?>
                </td>
                <td class="a-left">
                  <?php echo $_helper->getGroupHtmlSelect($_customer->getId(),$group_id,$_item->getItemId(),false); ?>
                  <input name="group_id" id="group_id" type="hidden" value="<?php echo $group_id ?>">
                </td>	
                <td class="a-center">
                  <?php if ($product->isSaleable()): ?>
                    <?php if ($isVisibleProduct): ?>
                      <button type="button" title="<?php echo $this->__('Add') ?>" onclick="setLocation('<?php echo $this->getUrl('*/*/cart', array('items' => $_item->getId(), 'groupId' => $group_id)) ?>')" class="button btn-cart"><span><span><?php echo $this->__('Add') ?></span></span></button>
					  <?php else: echo "Out of Stock"; ?>
                      <?php endif; ?>
                    <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>	
                    <?php endif; ?>	
                </td>	
                <td class="a-center"><a onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove item in this List?') ?>');" href="<?php echo $this->getRemoveItemUrl($group_id, $_item->getItemId())?>" title="<?php echo $this->__('Remove item')?>" class="btn-remove btn-remove2"><?php echo $this->__('Remove item')?></a></td>	
                <td class="a-center"><input type="checkbox" name="selectproduct" id="selectproduct" value="<?php echo $_item->getItemId();?>"/> </td>
              </tr>	
              <?php endforeach;?>
          </tbody>
        </table>
        <div class="buttons-set buttons-set2">
		<div style="width:200px; float:left; position:relative">
          <select name="choiceaction" id="choiceaction" onchange="choiceAction(this.value)" >
            <option value="0"><?php echo $this->__('Select Options') ?></option>-->
            <option value="delselect"><?php echo $this->__('Delete Selected Products') ?></option>
            <option value="addselect"><?php echo $this->__('Selected Products Add To Cart') ?></option>
          </select> </div>
          <button type="button" title="<?php echo $this->__('Add Product Select To Cart') ?>" onclick="if(getListProduct()==false){alert('Please select product want ADD TO CART')}else(setLocation('<?php echo $this->getUrl('*/*/cart');?>'+'?items='+getListProduct()+'&groupId='+<?php echo $group_id;?>))" class="button btn-add" id="addselecttocart" style="display: none;"><span><span><?php echo $this->__('Add Product Select To Cart') ?></span></span></button>
       <button type="button" title="<?php echo $this->__('Delete Products') ?>" onclick="if(getListProduct()==false){alert('Please select product want delete')}else(setLocation('<?php echo $this->getUrl('*/*/removeitem');?>'+'?id='+getListProduct()+'&group_id='+<?php echo $group_id;?>))" class="button btn-add" id="deleteselect" style="display: none;"><span><span><?php echo $this->__('Delete Products') ?></span></span></button>
 <button type="submit" title="<?php echo $this->__('Update Quick list') ?>" onclick="" class="button btn-update" style="float: left;"><span><span><?php echo $this->__('Update quick list') ?></span></span></button>
          <button type="button" title="<?php echo $this->__('Add All to Cart') ?>" style="float: left;" onclick="setLocation('<?php echo $this->getUrl('*/*/cart', array('items' => 'all', 'groupId' => $group_id)) ?>')" class="button btn-add"><span><span><?php echo $this->__('Add All to Cart') ?></span></span></button>
         
        </div>
        <?php else: ?>
        <input name="group_id" id="group_id" type="hidden" value="<?php echo $group_id ?>">          
        <p class="note-msg"><?php echo $this->__('There are no items in this List.') ?></p>
        <button type="submit" title="<?php echo $this->__('Update Quick List Title') ?>" onclick="" class="button btn-update" style="float: left;"><span><span><?php echo $this->__('Update Quick List Title') ?></span></span></button>   
        <?php endif; ?>
    </form>
  </div>
  <?php echo $this->getChildHtml('setting');?>
  <div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
  </div>
</div>
<script type="text/javascript">
  var listForm = new VarienForm('shoppinglist-group-view', true);
  function addItemToCart(submitUrl) {
    listForm.action = submitUrl;
    listForm.submit();
  }
  </script>