<?php
  /*
  * Copyright (c) 2013 www.magebuzz.com
  */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<ul class="add-to-links">
  <?php if ($this->helper('wishlist')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
    <?php endif; ?>
  <?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
  ?>
  <?php if($_compareUrl) : ?>
    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
    <?php endif; ?>

  <?php if (Mage::helper('shoppinglist')->isActive()) : ?>
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
      <?php $_shoppingListUrl = $this->getUrl('customer/account/login');?>
      <li><span class="separator">|</span> <a href="<?php echo  $this->getUrl('shoppinglist/item/login',array('id'=> $_product->getId(), 'type' => $_product->getTypeId())); ?>" class="link-shoppinglist" ><?php echo $this->__('Add to Shopping List') ?></a></li>
      <?php else:?>
      <?php $_shoppingListUrl = $this->getUrl('shoppinglist/index/additem');?>
      <li><span class="separator">|</span> <a href="" onclick="javascript:addToShoppingList('<?php echo $_shoppingListUrl;?>'); return false;" ><?php echo $this->__('Add to Shopping List') ?></a></li>
      <?php endif;?>
    <?php endif;?>
</ul>
<script type="text/javascript">
  function addToShoppingList(url) {
    var form = $('product_addtocart_form');
    if (form){
      var validator = new Validation(form);
      if (validator.validate()) {
        var data = form.serialize();
        jQ.colorbox({
          href:"<?php echo Mage::getUrl('shoppinglist/index/detailform/'); ?>"+ "?" +data
        });
      }
      //			
    }
    else
      document.location.href = url;      
    return false;
  }
</script>