<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @authors    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
<?php
    $_productCollection=$this->getFeaturedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<article class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
     
     <ul class="products-list" id="products-list" >
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                   
		    <div class="list-left">			
				<?php if($this->helper('framework')->isNewProduct($_product)):?>
					<div class="new-label"><?php echo $this->__('New') ?></div>
				<?php endif; ?>
					
				<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
					<div class="sale-label"><?php echo $this->__('Sale') ?></div>
				<?php endif; ?>
					
					
				<?php // Product Image ?>
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
			
			</div><!--- End list left  ---->
		   
		   <div class="list-center">
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                   
                   
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
												<?php if (Mage::helper('shoppinglist')->isActive() && $_product->isSaleable()) : ?>
                  <li>
                    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
                      <a href="<?php echo $this->getUrl('shoppinglist/item/login',array('id'=> $_product->getId(), 'type' => $_product->getTypeId())); ?>" id="openFormAdd" class="link-shoppinglist"><?php echo $this->__('Add to quick list') ?></a>
                      <?php else: ?>  
                      <a href="<?php echo Mage::getUrl('shoppinglist/index/add',array('id'=> $_product->getId(), 'type' => $_product->getTypeId())); ?>" id="openFormAdd" class="link-shoppinglist"><?php echo $this->__('Add to quick list') ?></a>
                      <?php endif; ?>         
                  </li>              
                  <?php endif; ?>
                       
                    </ul>
                </div>
				</div>
            </div><!--- End list center ---->
			
			<div class="list-right">
				 <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                   <?php endif; ?> 
			</div><!--- End list right  ---->
			
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
   
        <?php if ($i++%$_columnCount==0): ?>
        <ul id="featured_standalone_page" class="products-grid">
        <?php endif ?>
  	 <?php $i=0; foreach ($_productCollection as $_product): ?>          
		<li class="item">
		  <div class="product-block-image">
				<div class="product-block">
				<div class="product-block-inner">
				
				<?php if($this->helper('framework')->isNewProduct($_product)):?>
					<div class="new-label"><?php echo $this->__('New') ?></div>
				<?php endif; ?>
				
				<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
					<div class="sale-label"><?php echo $this->__('Sale') ?></div>
				<?php endif; ?>
				
			
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                
                
                <?php echo $this->getPriceHtml($_product, true) ?>
             
               <div class="hover_block">
							<div class="actions">
                               	 <ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
										<?php endif; ?>
										<?php if (Mage::helper('shoppinglist')->isActive() && $_product->isSaleable()) : ?>
                  <li>
                    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
                      <a href="<?php echo $this->getUrl('shoppinglist/item/login',array('id'=> $_product->getId(), 'type' => $_product->getTypeId())); ?>" id="openFormAdd" class="link-shoppinglist"><?php echo $this->__('Add to quick list') ?></a>
                      <?php else: ?>  
                      <a href="<?php echo Mage::getUrl('shoppinglist/index/add',array('id'=> $_product->getId(), 'type' => $_product->getTypeId())); ?>" id="openFormAdd" class="link-shoppinglist"><?php echo $this->__('Add to quick list') ?></a>
                      <?php endif; ?>         
                  </li>              
                  <?php endif; ?>
									</ul>
							</div>	
							 <?php if ($_product->isSaleable()): ?>
                                  
								  
								  
								   <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
 <div class="quantity">
<input type="text" name="qty" id="qty" maxlength="12" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
</div>
<button type="button" class="button btn-cart" onclick="productAddToCartForm_<?php echo $_product->getId(); ?>.submit()"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
</form>
<script type="text/javascript">
     var productAddToCartForm_<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
     productAddToCartForm_<?php echo $_product->getId(); ?>.submit = function(){
     if (this.validator.validate()) {
             this.form.submit();
         }
     }.bind(productAddToCartForm_<?php echo $_product->getId(); ?>);
</script>
								  
								  
								  
								  
                                <?php else: ?>
                                    <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
                                <?php endif; ?>
							
				</div>
				
				</div><!-- End div class product-block-->
				</div><!-- End div class product-block-inner -->
				</div>
            </li>
        <?php endforeach ?>   
        </ul>
        
     
        
		
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
	<span style="display: none; visibility: hidden;" class="grid_default_width"></span>
</article>
<?php endif; ?>


<script>
jQuery("div.quantity").append('<input type="button" value="+" id="add1" class="plus" />').prepend('<input type="button" value="-" id="minus1" class="minus" />');
        jQuery(".plus").click(function()
        {
            var currentVal = parseInt(jQuery(this).prev(".qty").val());
           
            if (!currentVal || currentVal=="" || currentVal == "NaN") currentVal = 0;
             
            jQuery(this).prev(".qty").val(currentVal + 1);
        });
     
        jQuery(".minus").click(function()
        {
            var currentVal = parseInt(jQuery(this).next(".qty").val());
            if (currentVal == "NaN") currentVal = 0;
            if (currentVal > 1)
            {
                jQuery(this).next(".qty").val(currentVal - 1);
            }
        });
         </script>