<?php
  /*
  * Copyright (c) 2013 www.magebuzz.com
  */

  $_customer = Mage::getSingleton('customer/session')->getCustomer();?>
<?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
  <?php $_product = $this->getProduct() ?>
  <form action="javascript:submitAddItem();" method="post" id="form-add-item">
    <div class="form-add">
      <h2 class="legend"><?php echo $this->__('Add item to Quick List') ?></h2>
      <ul class="form-list">
        <li class="fields">
          <div class="field">
            <?php //echo $this->getPriceHtml($_product);?>
          </div>
        </li>
        <li class="fields">
          <div class="field">
            <div class="pro-shop">
              <h5 id="product_name" class="product_name"><?php echo $_product->getName() ?></h5>
            </div>
            <?php //if ($_product->isSaleable()):?>
            <?php echo Mage::helper('shoppinglist')->getProductOptionsHtml($_product);?>
            <?php //endif;?>
          </div>
        </li>
        <li class="fields">
          <div class="field">
            <label class="required"><em>*</em><?php echo $this->__('Choose a Quick List')?></label>	
            <?php echo Mage::helper('shoppinglist/group')->getGroupHtmlSelect($_customer->getId(), null, null, true); ?>
          </div>	
        </li>
        <li class="control">
          <input type="checkbox" name="create_group" id="create_group" value="1" onclick="setCreateGroup(this.checked)" title="<?php echo $this->__('Create New Group') ?>" class="checkbox" /><label for="create_group"><?php echo $this->__('Create new Quick List') ?></label>
        </li>
        <li>
          <div id="form-create-group" style='display:none'>
            <label for="group-name" class="required"><em>*</em><?php echo Mage::helper('shoppinglist')->__('Group Name') ?></label>
            <div class="input-box">
              <input name="group-name" id="group-name" title="<?php echo Mage::helper('shoppinglist')->__('Group Name') ?>" value="" class="input-text required-entry" type="text" />
            </div>
          </div>
        </li>
        <li>
          <div class="field">
            <input name="customer_id" id="customer_id" type="hidden" value="<?php echo $_customer->getId()?>">
            <input name="product_id" id="product_id" type="hidden" value="<?php echo $_product->getId() ?>">
            <input name="product_type_id" id="product_type_id" type="hidden" value="<?php echo $_product->getTypeId() ?>">
            <input name="sold_out" id="sold_out" type="hidden" value="<?php echo $_REQUEST['soldout']; ?>">
          </div>
        </li>
      </ul>
      <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
        <button class="button btn-submit right" id="btn-submit-add-item" title="<?php echo $this->__('Submit')?>" type="submit">
          <span><span><?php echo $this->__('Submit')?></span></span>
        </button>
        <button onclick="javascript:resetFields();" class="button btn-reset right" id="btn-reset" title="<?php echo $this->__('Reset')?>" type="button">
          <span><span><?php echo $this->__('Reset')?></span></span>
        </button>
      </div>
    </div>
  </form>
  <?php else:?>
  <?php endif?>
<script type="text/javascript">
  //<![CDATA[
  var formAdd = new VarienForm('form-add-item', false);
  function resetFields() {
    Form.reset('form-add-item');
  }
</script>	